### ISSUE TITLE
Consider different approach/plugin for rendering API documentation

### ISSUE THREAD

**Issue by xgp** [p2-inc/phasetwo-docs#88]
The docusaurus openapi plugin we use has many bugs and isn't well-maintained https://github.com/cloud-annotations/docusaurus-openapi

Consider using vanilla swagger UI for API docs:
- in a separate github pages repo: https://github.com/peter-evans/swagger-github-pages
- as a react component inside `src/pages/api.js` https://www.npmjs.com/package/swagger-ui-react

**Comment by xgp** [comment]
Because of an incompatibility, the current plugin we use also prohibits us from upgrading docusaurus.

**Comment by hisorange** [comment]
Let me give a +1 to this. Just opened a silly ticket in the org plugin repo because the UI was a bit misleading.

Please see the image below, the response header which would tell the programmer that the resource will be identified at the new location is missing from the UI, is missing (green)
![Screenshot 2023-03-12 at 14 11 45](https://user-images.githubusercontent.com/3441017/224546942-825c9b6c-00b0-4ab1-80b1-66681e586a99.png)

But it is defined, and even well documented on the standard Swagger UI.
![Screenshot 2023-03-12 at 14 12 22](https://user-images.githubusercontent.com/3441017/224546968-3930401b-d836-4dd6-82cb-0b691651fbfe.png)


And the same goes for the `attributes` there is a helpful documentation which shows the values are a string array.

**Comment by xgp** [comment]
Related to https://github.com/p2-inc/phasetwo-docs/issues/53

**Comment by xgp** [comment]
We switched to this plugin https://github.com/PaloAltoNetworks/docusaurus-openapi-docs
Seems to have fewer bugs and sensible defaults.
